# Generated by Django 4.1.4 on 2022-12-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
