# Generated by Django 4.2.2 on 2023-07-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
